version: "3"

services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "3000:80"
    networks:
      - etec-app-network

  proxy:
    build:
      context: ./src/proxy  # Ruta corregida para el Dockerfile de proxy
    container_name: proxy
    ports:
      - "9090:80"  # El proxy se expone en el puerto 9090
    depends_on:
      - react-app
    networks:
      - etec-app-network

networks:
  etec-app-network:
    external: true
