version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend_proxy

  backend_proxy:
    image: nginx:alpine
    container_name: backend_proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

volumes:
  frontend_code:
  backend_code:
  db_data:
